language: node_js
node_js:
  - "6.9.4"

env:
  global:
  - CXX=g++-4.8
  - DEPLOY_BRANCH=master
  - secure: "ryj7ydOUtqiNXdhY4dvoFKuZhMD5jAaJk5O/LXIyKzfgA12geyzr4tjomNr1onHjE5yo+08SmVw9nGneNMQqPl69K3vvqVdf8ZCkA9vYaOFxBCK/0J7rW2bqh2qX4wTWvAbNyzzMfuXS8R/3kdN8tBG1GOyTO+4uk5OwG593WK8jz/tfInqPeuJ8VyO3rieQz6uOepmuFpK6P31+Co8xcSoXBopUrCmhmSmLPRDcG8bT3hE6/7tzZC7w0qT7w+7PwVV+T/A2MEqkN36O2nj9ywQZSflVMW2y5JVfqR2bA5zp0bAQxuBXqQu2rPWrxoQzO+DDOO53tuSPrTTfg0+/napq60cUElzYr5riGdxM89kV0JI0v7CpC6fqhwg32UzgIXGJKljygNhPztJpB9Wtr0ox7NiBuC8p/B0Vh1j7FKn61XUhbtGcBFsUNkAy6DjOLaH7765VwzKN3KR/Xqn7z/8/HfSbvcryK6UwAOzdN2q+dEcSTkS6hjiTR9HA4Aq0o9u0ziFDvrbQIPCPcmMsvKImKx2SFpn8cNWBtHeDAaiL/FqepFtpQI/9HDjSXA4Ikb0DOCJqEMv4JTwQi5zY/nIkT6T+ZekJoXRCaFTtgWJUqWxNifJWFbUgesraM0q3NWxCemB1qcgdrA42REcma2JEEgIOANHbIHhKRIva0Kw="
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

cache:
  apt: true
  directories:
    - node_modules

before_install:
- chmod +x ./.build_scripts/deploy.sh
- chmod +x ./.build_scripts/lint.sh

before_script:
- ./.build_scripts/lint.sh
- npm test

script:
- npm rebuild node-sass
- npm run build

deploy:
  provider: script
  skip_cleanup: true
  script: .build_scripts/deploy.sh
  on:
    branch: ${DEPLOY_BRANCH}
